default: true
no-hard-tabs: false
no-inline-html: false
single-h1:
  front_matter_title: ""
line-length: false
no-blanks-blockquote: false
no-trailing-punctuation: 
  punctuation: ".,;:。，；：！"

# MD013: { "line_length": 128 }
