baseURL = "https://www.jamestharpe.com/"
languageCode = "en-us"
title = "James Tharpe"
theme = "minimal"

[taxonomies]
    language = "languages"
    framework = "frameworks"
    tool = "tools"
    technique = "techniques"
    project = "projects"

[params]
    author = "James Tharpe"
    description = "Things I'm Learning"
    copyright = "Copyright &copy; James Tharpe; All rights reserved."
    githubUsername = "jamestharpe"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "c#", "kotlin", "css", "http", "ruby", "bash", "javascript", "groovy", "java", "json", "markdown", "powershell", "dockerfile"] # https://highlightjs.org/static/demo/

# [[menu.main]]
#     url = "/"
#     name = "Home"
#     weight = 1

[[menu.main]]
    url = "/languages/"
    name = "Languages"
    weight = 2

[[menu.main]]
    url = "/frameworks/"
    name = "Frameworks"
    weight = 3

[[menu.main]]
    url = "/tools/"
    name = "Tools"
    weight = 3

[[menu.main]]
    url = "/techniques/"
    name = "Techniques"
    weight = 4

[[menu.main]]
    url = "/hire-me/"
    name = "Hire Me"
    weight = 5

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:jimmy.tharpe@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/jamestharpe/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/jamestharpe/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/jamestharpe/"
    name = "linkedin"
    weight = 4

[[menu.icon]]
    url = "https://stackoverflow.com/users/104763/james"
    name = "stack-overflow"
    weight = 5
